<a href="https://colab.research.google.com/github/SimranKodwani-2003/Sabudh-Python-questions/blob/main/Python_Coursework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  ***LIST***

***Write a Python program to multiply all the items in a list***

In [ ]:
n=int(input("length of list"))
l=[]
for i in range(n):
  val=int(input("list Values"))
  l.append(val)
print(l)

length of list2
list Values1
list Values2
[1, 2]


In [ ]:
l=[1,2,3,4,5]
prod=1
for i in range(len(l)):
  prod=prod*l[i]
print(prod)

120


***Write a Python program to get the largest number from a list.\***


In [ ]:
l=[1,2,3,45,65]
m=max(l)
print(m)

65


***Write a Python program to get the smallest number from a list.***

In [ ]:
l=[10,20,30,40,50]
m=min(l)
print(m)

10


***Write a Python program to get a list, sorted in increasing order by the last element in each tuple from a given list of non-empty tuples.***

In [ ]:
# l = [29, 32, 12, 34, 20]
# sorted_l = sorted(l, key=lambda x: str(x)[-1])
# print(sorted_l)

[20, 32, 12, 34, 29]


In [ ]:
def Sort_Tuple(t):
    t.sort(key = lambda x: x[-1])
    return t

t = [(3, 1),(1, 3), (3, 2), (2, 1)]

print(Sort_Tuple(t))

[(3, 1), (2, 1), (3, 2), (1, 3)]


***Write a Python program to remove duplicates from a list.***

In [ ]:
l=[29, 32, 20, 12, 12, 34, 20]
s=set(l)
list(s)

[32, 34, 12, 20, 29]

**Write a Python program to check if a list is empty or not.
**

In [ ]:
l=[]
if len(l)==0:
  print("empty")
print(l)

empty
[]


*Write a Python program to count the lowercase letters in a given list ***

In [ ]:
string="SimranKodWaNi"
l=0
u=0
for i in string:
  if (i.islower()):
    l+=1
  else:
    u+=1
print(f"lower={l},upper={u}")


lower=9,upper=4


**Write a Python program to extract specified number of elements from a
given list, which follows each other continuously.<br>
○ Original list: [1, 1, 3, 4, 4, 5, 6, 7]<br>
○ Extract 2 number of elements from the said list which follows each
other continuously: [1, 4]<br><br>
○ Original list: [0, 1, 2, 3, 4, 4, 4, 4, 5, 7]<br>
○ Extract 4 number of elements from the said list which follows each
other continuously: [4]
**

In [ ]:
l =  [0, 1, 2, 3, 4, 4, 4, 4, 5, 7]
freq = {}

for i in range(len(l) - 1):
        freq[l[i]] = freq.get(l[i], 0) + 1

print(freq)
most_repeated = max(freq, key=freq.get)
most_repeated

{0: 1, 1: 1, 2: 1, 3: 1, 4: 4, 5: 1}


4

**Write a Python program to find the largest odd number in a given list of
integers.<br>
○ Sample Data: ([0, 9, 2, 4, 5, 6]) -> 9<br>
 ([-4, 0, 6, 1, 0, 2]) -> 1<br>
 ([1, 2, 3]) -> 3<br>
 ([-4, 0, 5, 1, 0, 1]) -> 5
 **

In [ ]:
def odd_find(n):
  even=[]
  odd=[]
  for i in range(len(n)-1):
    if n[i]%2==0:
      even.append(n[i])
    else:
      odd.append(n[i])
  print(max(odd))

k=odd_find([-4, 0, 5, 1, 0, 1])


5


**Write a Python program to print a specified list after removing the 0th, 4th
and 5th elements.
○ Sample List : [A, B, C, D, E, F]
○ Expected Output : [B, C, D]
**

In [ ]:
# def rem_Elem(n):
l=["A", "B", "C", "D", "E", 'F']
rm=[0,4,5]

f=[item for i,item in enumerate(l) if i not in rm]
f


['B', 'C', 'D']

#***Tuple***

**Write a Python program to create a tuple with different data types.
**

In [ ]:
t=(1,2,3,"h",True, [1, 2, 3], {'name': 'Simran'})
t

(1, 2, 3, 'h', True, [1, 2, 3], {'name': 'Simran'})

**Write a Python program to create a tuple of numbers and print one item.
**

In [ ]:
t=(1,28,56,4,5,6)
for i in range(len(t)-1):
  print(t[i])

1
28
56
4
5


**Write a Python program to add an item to a tuple.
**

In [ ]:
t=(1,2,3,"h")
l=list(t)
l.append("hello")
t=tuple(l)
t

(1, 2, 3, 'h', 'hello')

**Write a Python program to get the 4th element from the last element of a
Tuple.
**

In [ ]:
t=(1,2,3,"h","three",2003)
t[-4]

3

**Write a Python program to convert a tuple to a dictionary.
**

In [ ]:
t=(1,2,3,3,2,2,2003,2,6)
dict={}
for i in range(len(t)):
  if t[i] in dict:
      dict[t[i]]+=1
  else:
    dict[t[i]]=1
print(dict)

{1: 1, 2: 4, 3: 2, 2003: 1, 6: 1}


In [ ]:
t = (("name", "Simran"), ("age", 22), ("city", "Mumbai"))
dict_1 = dict(t)

print("Tuple to dict:", dict_1)


Tuple to dict: {'name': 'Simran', 'age': 22, 'city': 'Mumbai'}


**Write a Python program to replace the last value of tuples in a list.<br>
Sample list: [(10, 20, 40), (40, 50, 60), (70, 80, 90)]<br>
Expected Output: [(10, 20, 100), (40, 50, 100), (70, 80, 100)]
**

In [ ]:
t=[(10, 20, 40), (40, 50, 60), (70, 80, 90)]
l=list(t)
for i in range(len(t)):
  l[i] = l[i][:-1] + (100,)
print(l)

[(10, 20, 100), (40, 50, 100), (70, 80, 100)]


In [ ]:
l[0] = (10, 20, 40)
l[0][:-1]  # Output: (10, 20)  # Removes the last element

# ***DICTIONARY***:

*Write a Python script to sort (ascending and descending) a dictionary by
value.
**

In [ ]:
d={'b': 2, 'a': 1, 'c': 3}
s=dict(sorted(d.items(),key=lambda item: item[1]))
print(s)

{'a': 1, 'b': 2, 'c': 3}


In [ ]:
d={'b': 2, 'a': 1, 'c': 3}
s=dict(sorted(d.items(),key=lambda item: item[1],reverse=True))
print(s)

{'c': 3, 'b': 2, 'a': 1}


**Write a Python program to iterate over dictionaries using for loops.
**

In [ ]:
d={'a': 1, 'b': 2, 'c': 3}
for i in d:
    print(i,d[i])

a 1
b 2
c 3


**Write a Python script to merge two Python dictionaries.
**

In [ ]:
d1={'a': 1, 'b': 2, 'c': 3}
d2={'d': 4, 'e': 5, 'f': 5}
d1.update(d2)
d1

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 5}

**Write a Python program to sum all the items in a dictionary.
**

In [ ]:
d1={'a': 1, 'b': 2, 'c': 3}
d2={'a': 2, 'b': 2, 'c': 4}
# d1.update(d1.values)
sum(d1.values())+sum(d2.values())

14

In [ ]:
d = {'a': 10, 'b': 20, 'c': 30}
total = sum(d.values())
print(total)

60


**Write a Python program to multiply all the items in a dictionary.
**

In [ ]:
import math
d = {'a': 10, 'b': 20, 'c': 30}
total = math.prod(d.values())
print(total)

6000


** Write a Python program to sort a given dictionary by key.
**

In [ ]:
d={'b': 2, 'a': 4, 'c': 3}
s=dict(sorted(d.items()))
print(s)

{'a': 4, 'b': 2, 'c': 3}


**Write a Python program to remove duplicates from the dictionary.
**

In [ ]:
d={'b': 2, 'a': 4, 'c': 3, "a":2,'b': 2, 'a': 7, 'c': 3}
d=dict(set(d.items()))
d

{'b': 2, 'c': 3, 'a': 7}

# ***Numpy***

#  1. Numpy array creation and manipulation

**Create a 1D Numpy array “a” containing 10 random integers between 0 and 99.
**

In [15]:
a=np.random.randint(0,99,10)
a

array([71, 24, 62, 47,  7, 58, 91, 63, 45, 26])

**Create a 2D Numpy array “b” of shape (3, 4) containing random integers between -10
and 10.
**

In [16]:
b=np.random.randint(-10,10,(3,4))
b

array([[ 2, -6,  3,  8],
       [ 3,  4,  9, -8],
       [ 8, -6, -7,  7]])

**Reshape “b” into a 1D Numpy array “b_flat”
**

In [18]:
b.flatten()

array([ 2, -6,  3,  8,  3,  4,  9, -8,  8, -6, -7,  7])

**Create a copy of “a” called “a_copy”, and set the first element of “a_copy” to -1.
**

# **3. Numpy array operations**





*Create a 1D Numpy array “d” containing the integers from 1 to 10.***

In [5]:
import numpy as np
d=np.array([1,2,3,4,5,6,7,8,9,10])
print(d)

[ 1  2  3  4  5  6  7  8  9 10]


**Add “a” and “d” element-wise to create a new Numpy array “e”.
**

In [7]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
e = a + d
e


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

** Multiply “b” by 2 to create a new Numpy array “b_double"
**

In [8]:
b=np.array([1,2,3,4,5,6,7,8,9,10])
b_double=b*2
b_double

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

**Calculate the dot product of “b” and “b_double” to create a new Numpy array “f”.
**

In [9]:
f=b.dot(b_double)
f

770

**Calculate the mean of “a”,” b”, and “b_double” to create a new Numpy array “g”.
**

In [11]:
g=np.mean([a,b,b_double])
g

7.333333333333333